services:
  response-hub:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_ADVERSE_NEWS_API_URL=${VITE_ADVERSE_NEWS_API_URL}
    ports:
      - "3000:80"
    restart: unless-stopped
